restrict SAML service lookups to matching entityIDs
apereo/cas pull request #4951
Opened 2020-10-02 15:26 UTC by hsartoris-bard

Following the addition of `SamlIdPServicesManagerRegisteredServiceLocator`, unidentified service IDs are evaluated as possible SAML entityIDs against known SAML services, in addition to regular service ID matching as performed by `DefaultServicesManagerRegisteredServiceLocator`. This introduces an interesting failure case.

First, we need a SAML registered service that retrieves its metadata over MDQ, but it has not yet been retrieved, or the cached copy has expired. Now, we fire a request bearing a service ID not related to the SAML service; let's say it's not an entityID at all but a regular CAS service ID. What will happen is that, at some point, a call to `locate()` on `SamlIdPServicesManagerRegisteredServiceLocator` will fire in [`AbstractServicesManager`](https://github.com/apereo/cas/blob/0b3a7641e7e96a931c7a5577cd38ce0d1b106540/core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/AbstractServicesManager.java#L97), providing a predicate `entry -> entry.matches(serviceId)`. Before that predicate is evaluated, the candidates will be filtered by the BiPredicate on the extending class, which will dispatch a call to `SamlRegisteredServiceServiceProviderMetadataFacade.get`. After a series of attempted lookups, this will throw as no metadata is found - performing an MDQ lookup with the provided service ID is useless as it is not a SAML service. This will be logged as a failure to locate metadata for the *candidate* service, not the service ID being queried. 

This also extends into misconfigured SAML services - if one uses filesystem metadata, for example, that does not exist, it will fail every service (other than SAML services with higher precedence, I believe), which is not ideal.

There are a couple of ways to deal with this. The code I've changed here performs a check with `matches()` before actually doing any attempt to resolve the metadata. Another option would be to change the [filter order](https://github.com/apereo/cas/blob/0b3a7641e7e96a931c7a5577cd38ce0d1b106540/core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/DefaultServicesManagerRegisteredServiceLocator.java#L34-L35) on `DefaultServicesManagerRegisteredServiceLocator` to evaluate the provided Predicate first, but I feel this is making implicit in the usage pattern something that should be explicit: the server ought not to perform a costly metadata lookup if the entityID of the registered service does not even match the provided service ID. 

I believe this could be tested for by using Mockito in [SamlIdPServiceManagerRegisteredServiceLocatorTests](support/cas-server-support-saml-idp/src/test/java/org/apereo/cas/support/saml/services/SamlIdPServicesManagerRegisteredServiceLocatorTests.java) to ensure that `get` is not called on the metadataFacade, but haven't gotten that far yet.

2020-10-05 13:48 UTC, mmoayyed requested changes
Your description of the issue is fine, thank you. Please design test cases that align your description with an actual test scenario.

2020-10-16 11:10 UTC, mmoayyed requested changes

2020-10-16 11:10 UTC, mmoayyed commented on support/cas-server-support-saml-idp/src/test/java/org/apereo/cas/support/saml/services/SamlIdPServicesManagerRegisteredServiceLocatorTests.java
> +        }
You don't need this. Use mocks, and then do when(myresolver.resolve(...)).thenThrow()...

2020-10-16 11:10 UTC, mmoayyed commented on support/cas-server-support-saml-idp/src/test/java/org/apereo/cas/support/saml/services/SamlIdPServicesManagerRegisteredServiceLocatorTests.java
> +     * @author Hayden Sartoris
Remove author tag please, and put it at the top of the class instead.

2020-10-16 11:10 UTC, mmoayyed commented on support/cas-server-support-saml-idp/src/test/java/org/apereo/cas/support/saml/services/SamlIdPServicesManagerRegisteredServiceLocatorTests.java
> +        locator.locate(List.of(service1), service, r -> r.matches(entityID));
You must assert the result somehow to actually verify things. The verification might in fact be : "make sure nothing is thrown", etc. if that's what you're going for.

2020-10-16 11:10 UTC, mmoayyed commented on support/cas-server-support-saml-idp/src/test/java/org/apereo/cas/support/saml/services/SamlIdPServicesManagerRegisteredServiceLocatorTests.java
> +        SamlIdPServicesManagerRegisteredServiceLocator locator = new SamlIdPServicesManagerRegisteredServiceLocator(resolver);
Switch to `val`

2020-10-16 17:15 UTC, hsartoris-bard commented
Addressed the relevant issues (I think, though running the tests locally is still not working on my box)

2020-10-16 18:51 UTC, hsartoris-bard commented
Ok, so static mocks don't work without `mockito-inline`, which isn't that surprising, but I obviously shy away from wholesale changing over the mockito dependency for the entire project.

Unfortunately, mocking a resolver will not work, as the resolver must be passed to the locator as an argument, and the mocked resolver does not have the correct type.

2020-11-22 05:03 UTC, merged