Enabling Management Center scripting through property
apereo/cas pull request #4979
Opened 2020-11-13 11:25 UTC by rafiek

Enabling Management Center scripting is configured through the property `cas.ticket.registry.hazelcast.enable-management-center-scripting`. Kept the default to true to be consistent with previous version of the code.

2020-11-13 11:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/apereo/cas?pullRequest=4979) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/apereo/cas?pullRequest=4979) before we can accept your contribution.<br/><hr/>**rafiek** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/apereo/cas?pullRequest=4979) it.</sub>

2020-11-14 14:23 UTC, rafiek commented
@mmoayyed We found that there was no way to disable scripting through properties. We found that it was programmatically enabled. So this is a pull request to make it possible to enable/disable scripting through a property. We are in the middle of migrating from CAS5 to CAS6.2.x and stumbled on this one.

2020-11-16 11:32 UTC, mmoayyed commented on support/cas-server-support-hazelcast-core/src/main/java/org/apereo/cas/hz/HazelcastConfigurationFactory.java
> +        LOGGER.trace("Enables management center scripting: {}", hz.isEnableManagementCenterScripting());
```suggestion
        LOGGER.trace("Enables management center scripting: [{}]", hz.isEnableManagementCenterScripting());
```

2020-11-16 11:33 UTC, mmoayyed commented on support/cas-server-support-hazelcast-core/src/main/java/org/apereo/cas/hz/HazelcastConfigurationFactory.java
> +     */
```suggestion
```

2020-11-16 11:33 UTC, mmoayyed requested changes
Looks good, thank you!

Could you post the same PR for the master branch please?

2020-11-16 13:00 UTC, rafiek commented
> Looks good, thank you!
> 
> Could you post the same PR for the master branch please?

Thanks, will do! I am merging from 6.2.x branch into master, are you going to cherry-pick?

2020-11-16 13:05 UTC, mmoayyed commented
It would be best if you did a PR for master. You can cherry-pick this commit into a new branch.

2020-11-16 13:58 UTC, rafiek commented
> It would be best if you did a PR for master. You can cherry-pick this commit into a new branch.

PR is ready for master.

2020-11-16 17:33 UTC, merged