Turn off jasypt initialization vector by default
apereo/cas pull request #5025
Opened 2021-01-18 22:25 UTC by hdeadman

Having initialization vector used by default breaks passwords encrypted without it (e.g. in existing installations). This turns its use off by default but turns it on automatically for previously blacklisted algorithms that don't work without an initialization vector. Test added to make sure future changes don't break existing encrypted values, although the test only does so for a particular algorithm. 

There was a test already that would have caught this but it doesn't currently do a good job checking for errors:

https://github.com/apereo/cas/runs/1722512587?check_suite_focus=true#step:7:108

That isn't fixed by this PR but I will take a look at it.

2021-01-18 22:58 UTC, hdeadman commented
I updated the `validate-commandline-shell` so it should fail if there is a stack trace in any of the commands that are run.

2021-01-20 06:47 UTC, mmoayyed commented on api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/support/CasConfigurationJasyptCipherExecutor.java
> +    public boolean requiresInitializationVector(final String algorithm) {
Rename to `isVectorInitializationRequiredFor()`.

2021-01-20 06:48 UTC, mmoayyed commented on api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/support/CasConfigurationJasyptCipherExecutor.java
>           */
This javadoc should be moved to `StandaloneConfigurationSecurityProperties` instead, so metadata can pick it up for the docs and everywhere else.

2021-01-20 06:48 UTC, mmoayyed commented on api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/support/CasConfigurationJasyptCipherExecutor.java
> +            setInitializationVector();
Rename to `configureInitializationVendor()`. Set implies that you're passing a value as a setter.

2021-01-20 06:49 UTC, mmoayyed commented on api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/support/CasConfigurationJasyptCipherExecutor.java
> +         * An initialization vector must be enabled with `PBEWithDigestAndAES` algorithms that aren't BouncyCastle.
Please make sure all *code* elements, such as `PBEWithDigestAndAES `, are wrapped in `{@code xyz}`.

2021-01-20 06:49 UTC, mmoayyed requested changes
LGTM. Comments inline.

2021-01-20 06:51 UTC, mmoayyed commented on api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/support/CasConfigurationJasyptCipherExecutor.java
> +        INITIALIZATION_VECTOR("cas.standalone.configurationSecurity.initialization-vector", "false");
Also please add the new field to the above properties class. Without it, CAS will reject the setting and it will not show up in the docs anywhere.

2021-01-20 18:18 UTC, merged