Fix NPE in String find and match methods
apereo/cas pull request #5073
Opened 2021-03-08 17:35 UTC by pspaude

Currently null values break the find and match methods leading to unintended results (such as an error instead of MFA prompt in certain situations). Fixes these methods to be resilient.

2021-03-08 17:42 UTC, hdeadman commented
You don't often see catching of NullPointerException, why not check for the data that causes it, log a message and return false?

2021-03-08 18:43 UTC, pspaude commented
> You don't often see catching of NullPointerException, why not check for the data that causes it, log a message and return false?

Agree, I would actually like to catch all Exceptions which seems to match the intent, but since I didn't originally create these methods, I'm open to suggestions. If you don't think that's warranted, then yes I can create an if check for null input.

2021-03-08 22:01 UTC, hdeadman commented
What was the stack trace (i.e. who was calling the method with null)? Maybe this is a case where we want to fix the calling method to not pass null, and maybe the methods should have their parameters be annotated with `@NonNull` if they aren't going to work with null... Avoiding the NPE or catching exceptions is probably hiding some problem with the calling code....

2021-03-09 00:24 UTC, pspaude commented
> What was the stack trace (i.e. who was calling the method with null)? Maybe this is a case where we want to fix the calling method to not pass null, and maybe the methods should have their parameters be annotated with `@NonNull` if they aren't going to work with null... Avoiding the NPE or catching exceptions is probably hiding some problem with the calling code....

org.springframework.webflow.execution.ActionExecutionException: Exception thrown executing org.apereo.cas.web.flow.actions.CheckWebAuthenticationRequestAction@5a787684 in state 'determineDuoRequest' of flow 'mfa-duo' -- action execution attributes were 'map['resolvedAuthenticationEvents' -> list[mfa-duo]]'

                at org.springframework.webflow.execution.ActionExecutor.execute(ActionExecutor.java:62)

                at org.springframework.webflow.action.EvaluateAction.doExecute(EvaluateAction.java:77)

                at org.springframework.webflow.action.AbstractAction.execute(AbstractAction.java:188)

                at org.springframework.webflow.execution.AnnotatedAction.execute(AnnotatedAction.java:145)

                at org.springframework.webflow.execution.ActionExecutor.execute(ActionExecutor.java:51)

                at org.springframework.webflow.engine.ActionState.doEnter(ActionState.java:101)

                at org.springframework.webflow.engine.State.enter(State.java:194)

                at org.springframework.webflow.engine.Transition.execute(Transition.java:228)

                at org.springframework.webflow.engine.impl.FlowExecutionImpl.execute(FlowExecutionImpl.java:395)

                at org.springframework.webflow.engine.impl.RequestControlContextImpl.execute(RequestControlContextImpl.java:214)

                at org.springframework.webflow.engine.TransitionableState.handleEvent(TransitionableState.java:116)

                at org.springframework.webflow.engine.Flow.handleEvent(Flow.java:547)

                at org.springframework.webflow.engine.impl.FlowExecutionImpl.handleEvent(FlowExecutionImpl.java:390)

                at org.springframework.webflow.engine.impl.RequestControlContextImpl.handleEvent(RequestControlContextImpl.java:210)

                at org.springframework.webflow.engine.ActionState.doEnter(ActionState.java:105)

                at org.springframework.webflow.engine.State.enter(State.java:194)

                at org.springframework.webflow.engine.Transition.execute(Transition.java:228)

                at org.springframework.webflow.engine.impl.FlowExecutionImpl.execute(FlowExecutionImpl.java:395)

                at org.springframework.webflow.engine.impl.RequestControlContextImpl.execute(RequestControlContextImpl.java:214)

                at org.springframework.webflow.engine.TransitionableState.handleEvent(TransitionableState.java:116)

                at org.springframework.webflow.engine.Flow.handleEvent(Flow.java:547)

                at org.springframework.webflow.engine.impl.FlowExecutionImpl.handleEvent(FlowExecutionImpl.java:390)

                at org.springframework.webflow.engine.impl.RequestControlContextImpl.handleEvent(RequestControlContextImpl.java:210)

                at org.springframework.webflow.engine.ActionState.doEnter(ActionState.java:105)

                at org.springframework.webflow.engine.State.enter(State.java:194)

                at org.springframework.webflow.engine.Transition.execute(Transition.java:228)

                at org.springframework.webflow.engine.impl.FlowExecutionImpl.execute(FlowExecutionImpl.java:395)

                at org.springframework.webflow.engine.impl.RequestControlContextImpl.execute(RequestControlContextImpl.java:214)

                at org.springframework.webflow.engine.TransitionableState.handleEvent(TransitionableState.java:116)

                at org.springframework.webflow.engine.Flow.handleEvent(Flow.java:547)

                at org.springframework.webflow.engine.impl.FlowExecutionImpl.handleEvent(FlowExecutionImpl.java:390)

                at org.springframework.webflow.engine.impl.RequestControlContextImpl.handleEvent(RequestControlContextImpl.java:210)

                at org.springframework.webflow.engine.ActionState.doEnter(ActionState.java:105)

                at org.springframework.webflow.engine.State.enter(State.java:194)

                at org.springframework.webflow.engine.Transition.execute(Transition.java:228)

                at org.springframework.webflow.engine.impl.FlowExecutionImpl.execute(FlowExecutionImpl.java:395)

                at org.springframework.webflow.engine.impl.RequestControlContextImpl.execute(RequestControlContextImpl.java:214)

                at org.springframework.webflow.engine.TransitionableState.handleEvent(TransitionableState.java:116)

                at org.springframework.webflow.engine.Flow.handleEvent(Flow.java:547)

                at org.springframework.webflow.engine.impl.FlowExecutionImpl.handleEvent(FlowExecutionImpl.java:390)

                at org.springframework.webflow.engine.impl.RequestControlContextImpl.handleEvent(RequestControlContextImpl.java:210)

                at org.springframework.webflow.engine.ActionState.doEnter(ActionState.java:105)

                at org.springframework.webflow.engine.State.enter(State.java:194)

                at org.springframework.webflow.engine.Flow.start(Flow.java:527)

                at org.springframework.webflow.engine.impl.FlowExecutionImpl.start(FlowExecutionImpl.java:368)

                at org.springframework.webflow.engine.impl.RequestControlContextImpl.start(RequestControlContextImpl.java:234)

                at org.springframework.webflow.engine.SubflowState.doEnter(SubflowState.java:101)

                at org.springframework.webflow.engine.State.enter(State.java:194)

                at org.springframework.webflow.engine.Transition.execute(Transition.java:228)

                at org.springframework.webflow.engine.impl.FlowExecutionImpl.execute(FlowExecutionImpl.java:395)

                at org.springframework.webflow.engine.impl.RequestControlContextImpl.execute(RequestControlContextImpl.java:214)

                at org.springframework.webflow.engine.TransitionableState.handleEvent(TransitionableState.java:116)

                at org.springframework.webflow.engine.Flow.handleEvent(Flow.java:547)

                at org.springframework.webflow.engine.impl.FlowExecutionImpl.handleEvent(FlowExecutionImpl.java:390)

                at org.springframework.webflow.engine.impl.RequestControlContextImpl.handleEvent(RequestControlContextImpl.java:210)

                at org.springframework.webflow.engine.ActionState.doEnter(ActionState.java:105)

                at org.springframework.webflow.engine.State.enter(State.java:194)

                at org.springframework.webflow.engine.Flow.start(Flow.java:527)

                at org.springframework.webflow.engine.impl.FlowExecutionImpl.start(FlowExecutionImpl.java:368)

                at org.springframework.webflow.engine.impl.FlowExecutionImpl.start(FlowExecutionImpl.java:223)

                at org.springframework.webflow.executor.FlowExecutorImpl.launchExecution(FlowExecutorImpl.java:139)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                at java.base/java.lang.reflect.Method.invoke(Method.java:566)

                at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)

                at org.springframework.cloud.context.scope.GenericScope$LockedScopedProxyFactoryBean.invoke(GenericScope.java:499)

                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

                at org.springframewo [...]

2021-03-09 02:02 UTC, hdeadman commented
I think `CheckWebAuthenticationRequestAction` should handle requests with no content type specified. That field isn't mandatory and request.getContentType() returns null if no content type is specified.

2021-03-09 06:54 UTC, mmoayyed requested changes
It would be great to also include the stacktrace that caused the NPE so we can investigate the root cause. While the changes here are good defensive measures, they also only treat the symptom. If there is something in the code that is actually passing null and should not be doing it, we ought to review and adjust. (Defensive measures by themselves tend to make troubleshooting more difficult, since you'd never see the NPE and wouldn't know if there is a problem somewhere in the call stack)

2021-03-09 06:54 UTC, mmoayyed commented on core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/RegexUtils.java
> +        } catch (NullPointerException npe) {
Generally never a good idea to catch this. You should be simplify by using something like:

```
pattern != null and string != null and etc
```

2021-03-09 06:54 UTC, mmoayyed commented on core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/RegexUtils.java
> +            LOGGER.debug("Matching value [{}] against pattern [{}]", value, pattern.pattern());
Please switch this to trace.

2021-03-09 06:54 UTC, mmoayyed commented on core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/RegexUtils.java
> +            return pattern.matcher(string).find();
See earlier comment.

2021-03-09 06:54 UTC, mmoayyed commented on core/cas-server-core-util/src/test/java/org/apereo/cas/util/RegexUtilsTests.java
> +    @Test
Please also add a test where the pattern itself is null.

2021-03-09 14:39 UTC, mmoayyed commented
Thanks for providing the stacktrace. Somehow I missed it when I was doing the review. Sorry about the noise.

2021-03-28 08:11 UTC, pbodnar commented
Hi all, just a note: The stacktrace above shows only the case when null `string` parameter is passed to a method - that really should be handled. But it's not too likely that a null `pattern` will be given - I guess such a case doesn't have to be handled here.

Moreover, according to the original comment, it looks like we are talking actually about fixing some _bug_ in MFA at minimum, not just about refactoring. @pspaude, it would be great if you could share the exact scenarios when NPE occur now.

2021-03-28 16:42 UTC, hdeadman commented
I think @mmoayyed may have fixed the cause of this error in: https://github.com/apereo/cas/commit/88a62c9ed40d30568cc36f0126f72b089d1d5c9a#diff-b717e0c7da54fc97ea542719d9bb2f9280f0d1109e1d1a75dc6dd1bcec65c45f

There would still be an error thrown if null was passed to `RegexUtils.find` but I don't know if that is a bad thing... I would rather have it error out than hide what was probably a missing check by the caller.

2021-04-04 05:45 UTC, closed without merging