Fix reveal password button on mobile
apereo/cas pull request #5227
Opened 2021-09-15 09:46 UTC by vbonamy

On mobile, the "reveal password" button doesn't working.
This issue is described here : 
https://www.mail-archive.com/cas-user@apereo.org/msg11852.html
With this PR, we propose to modify the behaviorof this button on desktop so that it also works on mobile.
With this commit, you have to click once to see the password, and another time to hide it.

2021-09-15 09:48 UTC, mmoayyed requested changes
Thanks for the patch. 

Please include puppeteer tests to verify behavior, and then submit separate PRs for the master branch.

2021-09-16 08:13 UTC, vbonamy commented on ci/tests/puppeteer/scenarios/reveal-password/script.js
> +(async () => {
ignore

2021-09-16 13:09 UTC, vbonamy commented
So i added puppeteer tests, on 6.4.x it's working well.
_it seems that sonatype-lift can't parse well puppeteer scripts_ 
Thank you.

2021-09-16 13:10 UTC, mmoayyed commented
That is excellent, thank you. Please do the same sort of test on the other pull request, and don't worry about sonatype.

2021-09-19 03:55 UTC, merged