fix NullPointerException
apereo/cas pull request #5657
Opened 2023-06-02 10:08 UTC by ChaimNJ

exception.getMessage might be null.

2023-06-02 10:30 UTC, mmoayyed commented
Can you please explain how is it that `exception.getMessage might be null`? It might be null, yes, but how can it be null? Is the null message something that happens somewhere in the CAS codebase?

2023-06-02 10:31 UTC, mmoayyed requested changes

2023-06-02 10:31 UTC, mmoayyed commented on core/cas-server-core-util-api/src/test/java/org/apereo/cas/util/logging/DefaultLogMessageSummarizerTests.java
> +class DefaultLogMessageSummarizerTests {
Please make sure your test classes follow the same convention as every other class in the codebase and also run a style check on your changes.

2023-06-06 08:21 UTC, ChaimNJ commented
> Can you please explain how is it that `exception.getMessage might be null`? It might be null, yes, but how can it be null? Is the null message something that happens somewhere in the CAS codebase?



> Can you please explain how is it that `exception.getMessage might be null`? It might be null, yes, but how can it be null? Is the null message something that happens somewhere in the CAS codebase?

Sorry, I tried to reapprear this question, but it didn't appear.  The null message exception was catch at org.apereo.cas.web.flow.resolver.impl.DefaultCasDelegatingWebflowEventResolver#resolveInternal, I forgot what this exception is.  My CAS Version: 6.6.5

2023-06-06 08:53 UTC, mmoayyed commented
Thank you. Can you please also explain why the exception was thrown, and what was its exact type?

2023-06-06 12:35 UTC, closed without merging

2023-06-07 02:03 UTC, ChaimNJ commented
> Thank you. Can you please also explain why the exception was thrown, and what was its exact type?

I can't reproduce the exception, so i don‘t know the exact type. Related logs have been lost.  In my experience, the exception are thrown in my codebase,  not in the CAS codebase. I will keep an eye on this exception.