Fix authn delegation + throttling
apereo/cas pull request #5976
Opened 2024-01-24 12:58 UTC by leleuj

When using authn delegation, if a login is throtlled, the 423 error is returned and the `delegated-authn/casDelegatedAuthnStopWebflow.html` page is displayed instead of the `error/423.html` page.

This PR fixes the issue.

2024-01-24 13:40 UTC, leleuj commented
Backported to the 7.0 stream: https://github.com/apereo/cas/pull/5977

2024-01-24 14:35 UTC, mmoayyed requested changes
Thank you Jérôme, nicely done.

Does it make sense to add a puppeteer test? What we have here only simulates a failure.

2024-01-24 15:08 UTC, leleuj commented on support/cas-server-support-pac4j-core/src/main/java/org/apereo/cas/web/flow/error/DefaultDelegatedClientAuthenticationFailureEvaluator.java
> +            return Optional.of(new ModelAndView("error/423", new HashMap<>()));
Fixed

2024-01-24 15:08 UTC, leleuj commented on support/cas-server-support-pac4j-core/src/test/java/org/apereo/cas/web/flow/error/DefaultDelegatedClientAuthenticationFailureEvaluatorTests.java
> +        assertEquals("error/423", optModelAndView.get().getViewName());
Fixed

2024-01-24 15:10 UTC, leleuj commented
About the Puppeteer test, I had the feeling from my latest PRs that you wanted to limit them (to the main use cases). So I only added a unit test for this edge use case.
But I can of course add a Puppeteer test if you want.

2024-01-24 15:44 UTC, mmoayyed commented
If you find an existing puppeteer test case that is already setup for delegation and would be easy to add and test throttling with it, I'd say go for it. If not, at least for this case, I think it makes sense to create a brand new one. Having a unit test that does hit all the code paths is great/required, but in this case I am not sure it simulates the scenario well enough.

2024-01-24 15:44 UTC, mmoayyed commented
PS When you get to it, only do so for master please. No need to backport.

2024-01-25 06:19 UTC, leleuj commented
OK. I will take care of that.

2024-01-26 10:10 UTC, leleuj commented
@mmoayyed I just added a Puppeteer test: `authn-throttle-with-username-authndelegation-enabled` to confirm the fix.

A new test was necessary in order to add the `cas-server-support-pac4j-webflow` dependency.

2024-01-26 12:55 UTC, merged